# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rL4ZKDBcUJBdpGEuEg1VpIeDRtG6Wl-
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
from google.colab import drive
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (confusion_matrix, classification_report, accuracy_score,
                             roc_curve, auc, roc_auc_score)
import joblib

# =================================================================
# 1. KẾT NỐI DRIVE VÀ TẢI DỮ LIỆU
# =================================================================
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/school/Học phần tốt nghiệp/datasets/Student_Analytics_C++.csv'

try:
    df = pd.read_csv(file_path)
    df.columns = [c.lower().strip() for c in df.columns]
    print(">>> [OK] Tải dữ liệu thành công.")
    print(f"    Kích thước: {df.shape[0]} dòng × {df.shape[1]} cột")
except Exception as e:
    print(f">>> [ERROR] Lỗi tải file: {e}")
    raise

# =================================================================
# 2. XỬ LÝ DỮ LIỆU & GÁN NHÃN
# =================================================================
null_total = df.isnull().sum().sum()
print(f"\n>>> [PHÂN TÍCH] Tổng số giá trị trống trước xử lý: {null_total}")

# --- Gán nhãn ---
# 1 = Kém (weekly_score_w4 < 5.0), 0 = Đạt
if 'weekly_score_w4' not in df.columns:
    raise ValueError("Không tìm thấy cột 'weekly_score_w4' trong dữ liệu!")

df['label'] = (df['weekly_score_w4'] < 5.0).astype(int)
print(f"\n>>> [NHÃN] Phân phối nhãn:\n{df['label'].value_counts().rename({0:'Đạt (0)', 1:'Kém (1)'})}")

# --- Xây dựng danh sách features CHỈ từ W1, W2, W3 ---
metrics = [
    'active_days',
    'login_count',
    'video_views',
    'document_reads',
    'discussion',
    'assignment_duration_mins',  # thời gian làm bài — hành vi thực sự
    'ontime_margin',             # mức độ nộp đúng hạn — hành vi thực sự
    'days_since_last_login',
    'session_duration'
]

features_list = []
for w in [1, 2, 3]:             # CHỈ lấy W1, W2, W3 — không lấy W4
    for m in metrics:
        col = f'{m}_w{w}'
        if col in df.columns:
            features_list.append(col)

# =================================================================
# KIỂM TRA DATA LEAKAGE
# Đảm bảo không có cột W4 hoặc score nào lọt vào features
# =================================================================
leakage_cols = [f for f in features_list if 'w4' in f or 'score' in f]
if leakage_cols:
    print(f"\n>>> [CẢNH BÁO] Phát hiện data leakage! Loại bỏ: {leakage_cols}")
    features_list = [f for f in features_list if f not in leakage_cols]
else:
    print(f"\n>>> [OK] Không có data leakage. Tổng features: {len(features_list)}")

# --- Điền 0 cho giá trị trống (không hoạt động = 0) ---
df[features_list] = df[features_list].fillna(0)

# =================================================================
# 3. PHÂN TÍCH DỮ LIỆU KHÁM PHÁ (EDA)
# =================================================================
print("\n>>> Đang trực quan hóa dữ liệu (EDA)...")
plt.figure(figsize=(20, 5))

# Biểu đồ 1: Tỷ lệ Đạt/Kém
plt.subplot(1, 4, 1)
ax = sns.countplot(x='label', hue='label', data=df, palette='viridis', legend=False)
ax.set_xticks([0, 1])
ax.set_xticklabels(['Đạt (0)', 'Kém (1)'])
plt.title('Hình 1: Phân phối nhãn')

# Biểu đồ 2: Kiểm tra dữ liệu thiếu
plt.subplot(1, 4, 2)
sns.heatmap(df[features_list].isnull(), yticklabels=False, cbar=False, cmap='magma')
plt.title('Hình 2: Bản đồ dữ liệu thiếu')

# Biểu đồ 3: login_count_w3 vs Kết quả
plt.subplot(1, 4, 3)
sns.violinplot(x='label', y='login_count_w3', data=df, inner="quart")
plt.title('Hình 3: Đăng nhập W3 vs Kết quả')

# Biểu đồ 4: Xu hướng Active Days qua 3 tuần
plt.subplot(1, 4, 4)
active_cols = [c for c in ['active_days_w1', 'active_days_w2', 'active_days_w3'] if c in df.columns]
df_trend = df.groupby('label')[active_cols].mean().T
df_trend.index = ['W1', 'W2', 'W3']
plt.plot(df_trend[0], marker='s', label='Đạt (0)', color='green')
plt.plot(df_trend[1], marker='o', label='Kém (1)', color='red')
plt.title('Hình 4: Xu hướng hoạt động W1-W3')
plt.legend()

plt.tight_layout()
plt.show()

# =================================================================
# 4. CHIA DỮ LIỆU THEO LỚP (CROSS-CLASS VALIDATION)
# =================================================================
df['class_clean'] = df['class'].str.lower().str.strip()
all_classes = df['class_clean'].unique()
print(f"\n>>> [DỮ LIỆU] Các lớp hiện có: {sorted(all_classes)}")

train_classes = ['22ct111', '22ct112', '22ct113']
test_class    = '22ct114'

train_df = df[df['class_clean'].isin(train_classes)].copy()
test_df  = df[df['class_clean'] == test_class].copy()

print(f"    Train ({', '.join(train_classes)}): {len(train_df)} sinh viên")
print(f"    Test  ({test_class}):              {len(test_df)} sinh viên")

X_train = train_df[features_list]
y_train = train_df['label']
X_test  = test_df[features_list]
y_test  = test_df['label']

# Chuẩn hóa dữ liệu
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)   # fit + transform trên train
X_test_std  = scaler.transform(X_test)        # chỉ transform trên test

# =================================================================
# 5. HUẤN LUYỆN LOGISTIC REGRESSION
# =================================================================
model = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
model.fit(X_train_std, y_train)
print("\n>>> [OK] Huấn luyện mô hình hoàn tất.")

# =================================================================
# 6. ĐÁNH GIÁ MÔ HÌNH (ngưỡng mặc định 0.5)
# =================================================================
y_pred = model.predict(X_test_std)
y_prob = model.predict_proba(X_test_std)[:, 1]

print("\n" + "="*60)
print("KẾT QUẢ ĐÁNH GIÁ TRÊN TẬP KIỂM THỬ (LỚP 22CT114)")
print(f"Accuracy : {accuracy_score(y_test, y_pred):.4f}")
print(f"ROC-AUC  : {roc_auc_score(y_test, y_prob):.4f}")
print("="*60)
print(classification_report(y_test, y_pred, target_names=['Đạt (0)', 'Kém (1)']))

# --- Ma trận nhầm lẫn & ROC ---
plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='YlGnBu',
            xticklabels=['Đạt', 'Kém'], yticklabels=['Đạt', 'Kém'])
plt.title('Ma trận nhầm lẫn (ngưỡng mặc định 0.5)')
plt.xlabel('Kết quả dự đoán')
plt.ylabel('Kết quả thực tế')

plt.subplot(1, 2, 2)
fpr, tpr, _ = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', linestyle='--')
plt.title('Đường cong ROC')
plt.xlabel('Tỷ lệ Dương tính giả (FPR)')
plt.ylabel('Tỷ lệ Dương tính thật (TPR)')
plt.legend(loc="lower right")
plt.tight_layout()
plt.show()

# =================================================================
# FIX: TỐI ƯU NGƯỠNG QUYẾT ĐỊNH
# Tiêu chí: tối đa F1-score lớp Kém
# (cân bằng giữa Recall và Precision — tránh chọn ngưỡng quá thấp)
# =================================================================
print("\n>>> [TỐI ƯU NGƯỠNG] Tìm ngưỡng tốt nhất theo F1 lớp Kém...")

best_threshold = 0.5
best_f1        = 0.0
results        = []

for thresh in np.arange(0.20, 0.65, 0.05):
    y_pred_t = (y_prob >= thresh).astype(int)
    report   = classification_report(y_test, y_pred_t, output_dict=True, zero_division=0)

    if '1' in report:
        recall_1    = report['1']['recall']
        precision_1 = report['1']['precision']
        f1_1        = report['1']['f1-score']
        acc         = accuracy_score(y_test, y_pred_t)
        results.append({
            'Ngưỡng'       : round(thresh, 2),
            'Recall_Kém'   : round(recall_1, 3),
            'Precision_Kém': round(precision_1, 3),
            'F1_Kém'       : round(f1_1, 3),
            'Accuracy'     : round(acc, 3)
        })
        # Chọn ngưỡng có F1 cao nhất thay vì chỉ Recall
        if f1_1 > best_f1:
            best_f1        = f1_1
            best_threshold = round(thresh, 2)

results_df = pd.DataFrame(results)
print(results_df.to_string(index=False))
print(f"\n>>> [KẾT QUẢ] Ngưỡng tối ưu = {best_threshold} | F1(Kém) = {best_f1:.3f}")

# Đánh giá lại với ngưỡng tối ưu
y_pred_best = (y_prob >= best_threshold).astype(int)
print(f"\n--- Báo cáo với ngưỡng tối ưu ({best_threshold}) ---")
print(classification_report(y_test, y_pred_best, target_names=['Đạt (0)', 'Kém (1)']))

# So sánh confusion matrix: ngưỡng 0.5 vs ngưỡng tối ưu
plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
cm_05 = confusion_matrix(y_test, y_pred)
sns.heatmap(cm_05, annot=True, fmt='d', cmap='YlGnBu',
            xticklabels=['Đạt', 'Kém'], yticklabels=['Đạt', 'Kém'])
plt.title('Ngưỡng mặc định (0.5)')
plt.xlabel('Dự đoán'); plt.ylabel('Thực tế')

plt.subplot(1, 2, 2)
cm_best = confusion_matrix(y_test, y_pred_best)
sns.heatmap(cm_best, annot=True, fmt='d', cmap='Oranges',
            xticklabels=['Đạt', 'Kém'], yticklabels=['Đạt', 'Kém'])
plt.title(f'Ngưỡng tối ưu ({best_threshold})')
plt.xlabel('Dự đoán'); plt.ylabel('Thực tế')

plt.suptitle('So sánh Ma trận nhầm lẫn: Ngưỡng 0.5 vs Tối ưu', fontsize=13, y=1.02)
plt.tight_layout()
plt.show()

# =================================================================
# 7. PHÂN TÍCH TRỌNG SỐ (Ý NGHĨA SƯ PHẠM)
# =================================================================
coef_df = pd.DataFrame({'Feature': features_list, 'Weight': model.coef_[0]})
coef_df = coef_df.sort_values(by='Weight', ascending=False)
impact_df = pd.concat([coef_df.head(8), coef_df.tail(8)]).copy()

# Fix seaborn FutureWarning: dùng hue thay vì palette trực tiếp
impact_df['Loại'] = impact_df['Weight'].apply(
    lambda x: 'Tăng rủi ro' if x > 0 else 'Giảm rủi ro'
)

plt.figure(figsize=(10, 8))
sns.barplot(x='Weight', y='Feature', hue='Loại', data=impact_df,
            palette={'Tăng rủi ro': '#d9534f', 'Giảm rủi ro': '#5cb85c'},
            legend=False)
plt.title('Phân tích trọng số: Tăng rủi ro (Đỏ) vs Giảm rủi ro (Xanh)')
plt.axvline(x=0, color='black', lw=1)
plt.tight_layout()
plt.show()

print("\nTop 5 hành vi TĂNG nguy cơ học kém:")
print(coef_df.head(5)[['Feature', 'Weight']].to_string(index=False))
print("\nTop 5 hành vi GIẢM nguy cơ học kém:")
print(coef_df.tail(5)[['Feature', 'Weight']].to_string(index=False))

# =================================================================
# 8. LƯU MÔ HÌNH (bao gồm ngưỡng tối ưu)
# =================================================================
joblib.dump(model, 'logistic_student_model.pkl')
joblib.dump(scaler, 'scaler_student.pkl')
joblib.dump({
    'features' : features_list,
    'threshold': best_threshold
}, 'model_config.pkl')

print("\n>>> [HOÀN TẤT]")
print(f"- Mô hình  : 'logistic_student_model.pkl'")
print(f"- Scaler   : 'scaler_student.pkl'")
print(f"- Config   : 'model_config.pkl' (features + ngưỡng {best_threshold})")

# =================================================================
# 9. HÀM DỰ ĐOÁN SINH VIÊN MỚI
# =================================================================
def predict_student(student_data: dict) -> dict:
    """
    Dự đoán nguy cơ học kém cho một sinh viên mới.

    Tham số:
        student_data: dict với key là tên feature, value là giá trị hành vi
                      Ví dụ: {'login_count_w1': 5, 'active_days_w1': 3, ...}

    Trả về:
        dict: {'label': 0 hoặc 1, 'probability': float, 'risk': str}
    """
    config  = joblib.load('model_config.pkl')
    _model  = joblib.load('logistic_student_model.pkl')
    _scaler = joblib.load('scaler_student.pkl')

    # Tạo vector feature đúng thứ tự, điền 0 nếu thiếu
    row = [student_data.get(f, 0) for f in config['features']]
    X   = np.array(row).reshape(1, -1)
    X_s = _scaler.transform(X)

    prob  = _model.predict_proba(X_s)[0, 1]
    label = int(prob >= config['threshold'])

    return {
        'label'      : label,
        'probability': round(prob, 4),
        'risk'       : 'KÉM (cần hỗ trợ)' if label == 1 else 'ĐẠT'
    }

# Ví dụ sử dụng:
# result = predict_student({'login_count_w1': 2, 'active_days_w1': 1, ...})
# print(result)

print("\n>>> [TEMPLATE] Hàm predict_student() đã sẵn sàng sử dụng.")